import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { spaceGrostesk } from "@/components/font";
import { Toaster } from "sonner";

export const metadata: Metadata = {
   title: "Chating | Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" suppressHydrationWarning>
         <body className={spaceGrostesk.className}>
            <ThemeProvider attribute="class" defaultTheme="dark">
               {children}
               <Toaster position="top-right" />
            </ThemeProvider>
         </body>
      </html>
   );
}
